version: '3.3'
services:
  prometheus:
    image: prom/prometheus:latest
    restart: always
    volumes:
      - './prometheus:/etc/prometheus'
      - './data/prometheus:/prometheus/data'
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - '9090:9090'
  node-exporter:
    image: prom/node-exporter:latest
    restart: always

  grafana:
    image: grafana/grafana:latest
    restart: always
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=pass
    volumes:
      - ./grafana/:/etc/grafana/provisioning/
      - ./data/grafana/data/:/var/lib/grafana
      - ./data/grafana/log/:/var/log/grafana
    depends_on:
      - prometheus
    ports:
      - "3000:3000"


  teku:
    image: consensys/teku:develop
    restart: always
    user: '501'
    cap_add:
      - ALL
    environment:
      - 'JAVA_OPTS=-XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/data -Xmx3g -XX:SoftMaxHeapSize=500m -Djdk.nio.maxCachedBufferSize=1 -XX:+UseContainerSupport -XX:MinHeapFreeRatio=20 -XX:MaxHeapFreeRatio=30'

    command:
      - "--network=/config/config.yaml"
      - "--p2p-discovery-bootnodes=enr:-Iq4QMCTfIMXnow27baRUb35Q8iiFHSIDBJh6hQM5Axohhf4b6Kr_cOCu0htQ5WvVqKvFgY28893DHAg8gnBAXsAVqmGAX53x8JggmlkgnY0gmlwhLKAlv6Jc2VjcDI1NmsxoQK6S-Cii_KmfFdUJL2TANL3ksaKUnNXvTCv1tLwXs0QgIN1ZHCCIyk"
      - "--initial-state=/config/genesis.ssz"
      - "--rest-api-enabled"
      - "--rest-api-docs-enabled"
      - "--rest-api-host-allowlist=*"
      - "--metrics-enabled"
      - "--metrics-host-allowlist=*"
      - "--eth1-endpoint=http://eth1:8545"
      - "--ee-endpoint=http://eth1:8551"
      - "--ee-jwt-secret-file=/jwt/secret.hex"
      - "--log-file=/data/teku.log"
      - "--data-path=/data"

    volumes:
      - './data/teku:/data'
      - '../merge-testnets/goerli-shadow-fork-1:/config'
      - './data/jwt:/jwt'
    ports:
      - "9000:9000/tcp"
      - "9000:9000/udp"
      - "5051:5051"
      - "8008:8008"

  eth1:
    image: ethereum/client-go:latest
    restart: always
    user: '501'
    cap_add:
      - ALL
    command:
      - "--datadir=/data"
      - "--bootnodes=enode://451e82bd12e683bbdda82bcd90cc1c84d33323c1903542b6c49db3ace071a9cd54bca243f9b6836d90629a9a74d396c5315fca115a84cda7af6522202ffd7b28@164.90.177.4:3030,enode://c6dc3f624a4ccd6a49d0330dda575ced70f022d02bd28f85689d8cb69ad28703e6f86415be6f36aa7c9d72601511658ac3afb349ffe16479287e5b85a272b705@64.227.163.30:30303,enode://bfc96cba03ee2e9582bff10ff5f7f0acf5778933053176a130b3a1adef9deefa0f8fbdd182c24c0897821b51528164f76545aaa9ea1ea68e1243633051a9f66e@164.90.163.145:30303,enode://abd62b19a7029e562ad099bc7d8411b8dd79829e3ff616f2223101fcc254ed70e6485b10166411e2296503cbacb7b555d221fa549facb502838e8f92eae420b0@165.227.120.76:30303"
      - "--networkid=5"
      - "--http"
      - '--http.api="engine,eth,web3,net,debug,admin"'
      - '--http.corsdomain="*"'
      - '--authrpc.jwtsecret=/jwt/secret.hex'
    volumes:
      - './data/geth:/data'
      - '../merge-testnets/goerli-shadow-fork-1:/config'
      - './data/jwt:/jwt'
    ports:
      - 30303
      - 8545
