# prometheus.yml
global:
  scrape_interval: 5s
  external_labels:
    monitor: 'my-monitor'
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
  - job_name: 'teku'
    static_configs:
      - targets: ['teku:8008']
  - job_name: eth1
    # Required for Geth:
    #metrics_path: /debug/metrics/prometheus
    static_configs:
      - targets: ['eth1:9545']
